# Generated by Django 5.0.3 on 2024-03-11 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='info',
            new_name='description',
        ),
        migrations.AddField(
            model_name='home',
            name='additional_photos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='category',
            field=models.CharField(default='placeholder', max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='contact_button_text',
            field=models.CharField(default='Contact', max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
