# Generated by Django 5.0.3 on 2024-03-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_info_home_description_home_additional_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='created_on',
        ),
    ]
