# Generated by Django 5.0.3 on 2024-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_home_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='description',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='home',
            name='additional_photos',
        ),
        migrations.RemoveField(
            model_name='home',
            name='contact_button_text',
        ),
        migrations.RemoveField(
            model_name='home',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='home',
            name='user',
        ),
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
